name: srv-robotic-platform
group: robotic-framework
owner: robotic-framework
version: 0.0.0
description: 机器人管理控制平台
program_language: golang
workflow:
  extends: feature-pr
scripts:
  build:
  - go build -v -o ./build/$PROJECT_NAME -ldflags "-X github.com/eden-framework/apollo.Branch=$DRONE_BRANCH.json"
    ./cmd
  - eden generate openapi
  test: go test ./cmd
